---
title: "week2-exercise"
author: "Javier Patron"
date: "2023-04-10"
output: html_document
---

## Text Analysis

```{r}
# Load in the libraries
library(tidytext)
library(tidyverse)
library(here)
```


```{r}

# Set the working directory and create a table that contains the text from each file
setwd("/Users/javipatron/Documents/MEDS/Courses/eds231/text_modeling-lab2/spring_text")

tbl <- list.files() |> 
  map_chr(~read_file((.))) 

x <- tibble(text = tbl)

```


```{r}
# Create a new table that has
text_words <- x |> 
  unnest_tokens(word, text)
```

```{r}
text_words |> 
  count(word, sort = T) |> 
  filter(n > 22) |> 
  mutate(word = reorder(word, n)) |> 
  ggplot(aes(n,word)) +
  geom_col() +
  labs(y =NULL)

```


```{r}

# Cleaning the words that are not useful. The top_words has a listo of words that are not normally useful and that is why you use the anti_join
data(stop_words)
dim(stop_words)

text_words <- text_words |> 
  anti_join(stop_words)


```


```{r}
# Load the bing data
bing_sent <- get_sentiments("bing") 
dim(bing_sent)


# Add the positive or negative information from "bing
text_words |> 
  inner_join(bing_sent)

```


```{r}
# A table with sentiments that have particular emotional correlated to words
nrc_joy <- get_sentiments("nrc") |> 
  filter(sentiment == "joy") 

text_words |> 
  inner_join(nrc_joy) |> 
  count(word, sort = T)

```


